Cpp cache
resonai/ybt pull request #221
Opened 2021-11-23 08:23 UTC by dana-resonai

* Add possibility for the plugins to implement cache_json func
* Extract utility function `compute_target_json`
* Implement the different cache json of cpp
* Use the cache_json func of targets if it exists

2021-11-24 12:38 UTC, dana-resonai commented
I ran this with one of our big targets.
In master rebuild after a small change in a .cc file took 1.5 minutes
In this branch rebuild after a small change in a .cc file took 0.5 minutes

2021-11-24 12:38 UTC, dana-resonai commented
I ran this with one of our big targets.
In master rebuild after a small change in a .cc file took 1.5 minutes
In this branch rebuild after a small change in a .cc file took 0.5 minutes

2021-11-24 15:38 UTC, dlehavi-resonai requested changes

2021-11-24 15:38 UTC, dlehavi-resonai commented on yabt/builders/cpp.py
> +
Please *heavily* document the decisions made here: the details are obvious if you understand them and completely cryptic otherwise

2021-11-29 06:51 UTC, eyal-resonai commented on yabt/builders/cpp_caching_test.py
>  def test_caching_prog(tmp_dir):
I'm missing a tests which tests the new functionality (or am i missing it?)

2021-11-29 07:48 UTC, eyal-resonai approved these changes

2021-11-29 08:47 UTC, dlehavi-resonai approved these changes

2021-11-29 08:55 UTC, merged