python test link in build
resonai/ybt pull request #236
Opened 2022-05-26 14:55 UTC by dana-resonai

move the linking of all the relevant files to the python test target directory to run on build and not on test.

The reason for this:
First, it makes more sense that the build phase is in charge to pack all the dependencies in one place.
Second, this allows us to run ybt build on the test target and then manually run the test command with the relevant docker & mappings (as we do in cpp test)

Please let me know if there is any good reason not to move it.

This will help both @shirl-resonai and @amirbennatan

2022-05-29 03:45 UTC, itamaro requested changes
I don't have any objection to this change - just make sure the tests are happy :)

2022-05-29 15:34 UTC, dlehavi-resonai commented
@itamaro it was some travis and appveyor issues both of which I resolved in a separate PR: travis had a problem with egg_info in 3.7, and appveyor had some issue with the entire concept of 3.5; I have to say I agree with it: I have a problem with the entire concept of python.

2022-05-29 15:45 UTC, shirl-resonai approved these changes

2022-05-29 15:49 UTC, merged

2022-05-29 16:57 UTC, itamaro commented
> I have a problem with the entire concept of python

The story of my life

2022-06-02 04:14 UTC, eyal-resonai commented
I think this is broken due to bad interaction with global cache - when we have a global cache for the python test (and no local one) we are not fetching all the needed files to allow the test to run.